---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress 
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - image: wordpress:6.8.1-apache
          name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: wordpress-configmap
                  key: wp_db_host
            - name: WORDPRESS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: wordpress-configmap
                  key: wp_db_name
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: wordpress-auth
                  key: wp_db_username
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-auth
                  key: wp_db_password
            - name: WORDPRESS_CONFIG_EXTRA
              value: "define('FS_METHOD', 'direct');"
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: wp-pv-volume
              mountPath: /var/www/html
      volumes:
        - name: wp-pv-volume
          persistentVolumeClaim:
            claimName: wordpress-pv-claim 
