apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress
  namespace: wordpress
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
spec:
  ingressClassName: nginx
  rules:
  - host: k8s-prod-1.encrypted.my
    http:
       paths:
        - path: /
          pathType: Prefix
          backend:
           service:
            name: wordpress-svc
            port:
             name: http
  tls:
    - hosts:
      - k8s-prod-1.encrypted.my
      secretName: letsencrypt-prod
