---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-da463b53-7b9d-40e0-9a47-6e1ae31eb046
  annotations:
    pv.kubernetes.io/provisioned-by: driver.longhorn.io
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  volumeMode: Filesystem
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: pvc-da463b53-7b9d-40e0-9a47-6e1ae31eb046
    volumeAttributes:
      backupTargetName: default
      dataEngine: v1
      dataLocality: disabled
      disableRevisionCounter: "true"
      fromBackup: ""
      fsType: ext4
      numberOfReplicas: "3"
      staleReplicaTimeout: "30"
      storage.kubernetes.io/csiProvisionerIdentity: 1772295534452-1754-driver.longhorn.io
      unmapMarkSnapChainRemoved: ignored
  claimRef:
    namespace: wordpress
    name: wordpress-pv-claim

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pv-claim
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: pvc-da463b53-7b9d-40e0-9a47-6e1ae31eb046
  resources:
    requests:
      storage: 5Gi
