---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-da463b53-7b9d-40e0-9a47-6e1ae31eb046
  annotations:
    pv.kubernetes.io/provisioned-by: driver.longhorn.io
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  volumeMode: Filesystem
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: pvc-da463b53-7b9d-40e0-9a47-6e1ae31eb046
    volumeAttributes:
      numberOfReplicas: "2"
      staleReplicaTimeout: "30"
      fsType: ext4
  claimRef:
    namespace: wordpress
    name: wordpress-pv-claim

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pv-claim
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: pvc-da463b53-7b9d-40e0-9a47-6e1ae31eb046
  resources:
    requests:
      storage: 5Gi
